services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  gateway:
    build:
      context: ./gateway-server
    container_name: gateway
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth:8001
      - EVENT_SERVICE_URL=http://event:8002
    depends_on:
      - auth
      - event
      - mongodb
  auth:
    build:
      context: ./auth-server
    container_name: auth
    restart: always
    ports:
      - '8001:8001'
    environment:
      - PORT=8001
      - MONGODB_URI=mongodb://mongodb:27017/auth
    depends_on:
      - mongodb

  event:
    build:
      context: ./event-server
    container_name: event
    restart: always
    ports:
      - '8002:8002'
    environment:
      - PORT=8002
      - MONGODB_URI=mongodb://mongodb:27017/event
    depends_on:
      - mongodb

volumes:
  mongodb_data:
